// ============================================================
// Demo / Seed Data for development and preview
// ============================================================
import type {
  Profile, Department, ResearchProject, Notification,
  ActivityLog, DashboardStats, AIInsight
} from '@/types'

export const DEMO_DEPARTMENTS: Department[] = [
  { id: 'd1', name: 'Internal Medicine', code: 'INT-MED', color: '#2563eb', icon: 'stethoscope', research_count: 12, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd2', name: 'Surgery', code: 'SURG', color: '#dc2626', icon: 'scissors', research_count: 8, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd3', name: 'Pediatrics', code: 'PEDI', color: '#16a34a', icon: 'baby', research_count: 10, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd4', name: 'Emergency', code: 'EMRG', color: '#ea580c', icon: 'alert-triangle', research_count: 6, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd5', name: 'ICU', code: 'ICU', color: '#7c3aed', icon: 'activity', research_count: 7, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd6', name: 'Nursing', code: 'NURS', color: '#e11d48', icon: 'heart', research_count: 15, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd7', name: 'Cardiology', code: 'CARD', color: '#dc2626', icon: 'heart-pulse', research_count: 9, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd8', name: 'Pharmacy', code: 'PHRM', color: '#65a30d', icon: 'pill', research_count: 5, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd9', name: 'Radiology', code: 'RADI', color: '#0891b2', icon: 'scan', research_count: 4, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd10', name: 'Laboratory', code: 'LAB', color: '#d97706', icon: 'flask-conical', research_count: 11, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd11', name: 'Neurology', code: 'NEUR', color: '#7c3aed', icon: 'brain', research_count: 6, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd12', name: 'Orthopedics', code: 'ORTH', color: '#0d9488', icon: 'bone', research_count: 5, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd13', name: 'OB/GYN', code: 'OBGYN', color: '#c026d3', icon: 'baby', research_count: 7, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
  { id: 'd14', name: 'Administration', code: 'ADMIN', color: '#475569', icon: 'building', research_count: 3, is_active: true, created_at: '2024-01-01', updated_at: '2024-01-01' },
]

export const DEMO_USERS: Profile[] = [
  {
    // Initial Super Admin per spec — must be created by the admin process.
    // Username collision resolution: spec's Option A (auto-generate from name).
    id: 'u1',
    username: 'sultan.alallah',
    full_name: 'Sultan Alallah',
    email: 'admin@pmnh.gov.sa',
    phone: '+966501283990',
    role: 'super_admin',
    department_id: 'd14',
    is_active: true,
    email_verified: true,
    phone_verified: true,
    login_count: 0,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
  {
    id: 'u2',
    username: 'dr.fatima.director',
    full_name: 'Dr. Fatima Al-Zahrani',
    email: 'director@pmnh.gov.sa',
    phone: '+966500112233',
    role: 'research_director',
    department_id: 'd14',
    is_active: true,
    email_verified: true,
    phone_verified: true,
    login_count: 89,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
    last_login: '2026-05-17T10:15:00Z',
  },
  {
    id: 'u3',
    username: 'dr.khalid.surgery',
    full_name: 'Dr. Khalid Al-Ghamdi',
    email: 'khalid@pmnh.gov.sa',
    phone: '+966555443322',
    role: 'department_head',
    department_id: 'd2',
    is_active: true,
    email_verified: true,
    phone_verified: false,
    login_count: 67,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
    last_login: '2026-05-16T09:45:00Z',
  },
  {
    // Initial Admin per spec — Option-A unique alias for the duplicate
    // "Research Unit" username.
    id: 'u4',
    username: 'afnan.bakri',
    full_name: 'Afnan Bakri',
    email: 'bkriafnan@gmail.com',
    phone: '+966532856572',
    role: 'admin',
    department_id: 'd6',
    is_active: true,
    email_verified: true,
    phone_verified: true,
    login_count: 0,
    created_at: '2024-01-01',
    updated_at: '2024-06-01',
  },
]

export const DEMO_RESEARCH: ResearchProject[] = [
  {
    id: 'r1',
    research_id: 'PMNH-2024-0001',
    title: 'Assessment of Hypertension Management Protocols in ICU Patients',
    abstract: 'A comprehensive study evaluating the effectiveness of current hypertension management protocols in ICU settings at Prince Mohammed Bin Nasser Hospital.',
    research_category: 'Clinical Research',
    department_id: 'd5',
    principal_investigator_name: 'Dr. Ahmed Al-Qahtani',
    start_date: '2024-01-15',
    expected_completion_date: '2025-01-15',
    status: 'completed',
    workflow_stage: 'published',
    priority_level: 'high',
    completion_percentage: 100,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'approved',
    funding_source: 'Ministry of Health',
    budget: 85000,
    budget_currency: 'SAR',
    publication_status: 'published',
    journal_name: 'Saudi Medical Journal',
    publication_date: '2025-02-10',
    doi: '10.2471/BLT.24.001234',
    impact_factor: 2.4,
    citation_count: 5,
    journal_quartile: 'Q2',
    indexed_database: 'Scopus',
    is_open_access: true,
    is_public: true,
    is_archived: false,
    notes: 'Published successfully in Saudi Medical Journal.',
    created_at: '2024-01-15',
    updated_at: '2025-02-15',
  },
  {
    id: 'r2',
    research_id: 'PMNH-2024-0002',
    title: 'Nursing Staff Burnout and Patient Safety Outcomes in Emergency Departments',
    abstract: 'Investigating the relationship between nursing staff burnout levels and patient safety outcomes in emergency department settings.',
    research_category: 'Nursing Research',
    department_id: 'd6',
    principal_investigator_name: 'Sara Al-Malki',
    start_date: '2024-03-01',
    expected_completion_date: '2025-03-01',
    actual_completion_date: undefined,
    status: 'delayed',
    workflow_stage: 'data_analysis',
    priority_level: 'critical',
    completion_percentage: 65,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'approved',
    funding_source: 'Hospital Research Fund',
    budget: 45000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_quartile: 'not_indexed',
    indexed_database: 'not_indexed',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    notes: 'Data collection extended due to staff shortages. Analysis phase ongoing.',
    created_at: '2024-03-01',
    updated_at: '2026-04-20',
  },
  {
    id: 'r3',
    research_id: 'PMNH-2024-0003',
    title: 'Antibiotic Resistance Patterns in Post-Surgical Infections',
    abstract: 'Analysis of antibiotic resistance patterns in patients developing post-surgical infections over a 24-month period.',
    research_category: 'Clinical Research',
    department_id: 'd2',
    principal_investigator_name: 'Dr. Khalid Al-Ghamdi',
    start_date: '2024-02-15',
    expected_completion_date: '2025-08-15',
    status: 'active',
    workflow_stage: 'manuscript_writing',
    priority_level: 'high',
    completion_percentage: 80,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'approved',
    funding_source: 'King Abdulaziz City for Science and Technology',
    budget: 120000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_name: 'Journal of Hospital Infection',
    journal_quartile: 'Q1',
    indexed_database: 'Scopus',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    created_at: '2024-02-15',
    updated_at: '2026-05-01',
  },
  {
    id: 'r4',
    research_id: 'PMNH-2024-0004',
    title: 'Pediatric Obesity Prevalence and Dietary Interventions in Jazan Region',
    abstract: 'A population-based study assessing pediatric obesity prevalence and testing dietary intervention programs in the Jazan region.',
    research_category: 'Epidemiology',
    department_id: 'd3',
    principal_investigator_name: 'Dr. Fatima Al-Zahrani',
    start_date: '2024-04-01',
    expected_completion_date: '2026-04-01',
    status: 'active',
    workflow_stage: 'data_collection',
    priority_level: 'medium',
    completion_percentage: 40,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'pending',
    funding_source: 'WHO Regional Office',
    budget: 200000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_quartile: 'not_indexed',
    indexed_database: 'not_indexed',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    created_at: '2024-04-01',
    updated_at: '2026-03-15',
  },
  {
    id: 'r5',
    research_id: 'PMNH-2025-0005',
    title: 'Cardiac Rehabilitation Program Effectiveness Post-CABG Surgery',
    abstract: 'Evaluating structured cardiac rehabilitation outcomes in patients 12 months post Coronary Artery Bypass Graft surgery.',
    research_category: 'Clinical Research',
    department_id: 'd7',
    principal_investigator_name: 'Dr. Mohammed Al-Asiri',
    start_date: '2025-01-10',
    expected_completion_date: '2026-07-10',
    status: 'active',
    workflow_stage: 'data_collection',
    priority_level: 'high',
    completion_percentage: 30,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'approved',
    funding_source: 'King Faisal Specialist Hospital Collaboration',
    budget: 180000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_name: 'European Heart Journal',
    journal_quartile: 'Q1',
    indexed_database: 'ISI',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    created_at: '2025-01-10',
    updated_at: '2026-05-01',
  },
  {
    id: 'r6',
    research_id: 'PMNH-2025-0006',
    title: 'Impact of Telemedicine on Chronic Disease Management in Rural Jazan',
    abstract: 'Assessment of telemedicine consultation effectiveness on hypertension and diabetes management in rural communities within Jazan region.',
    research_category: 'Public Health',
    department_id: 'd1',
    principal_investigator_name: 'Dr. Nora Al-Shahrani',
    start_date: '2025-03-01',
    expected_completion_date: '2026-09-01',
    status: 'active',
    workflow_stage: 'proposal_drafted',
    priority_level: 'medium',
    completion_percentage: 15,
    irb_approval_status: 'pending',
    department_approval_status: 'approved',
    ethics_approval_status: 'pending',
    funding_source: 'Saudi Digital Health Authority',
    budget: 250000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_quartile: 'not_indexed',
    indexed_database: 'not_indexed',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    notes: 'IRB approval pending. Expected approval within 2 weeks.',
    created_at: '2025-03-01',
    updated_at: '2026-04-25',
  },
  {
    id: 'r7',
    research_id: 'PMNH-2023-0007',
    title: 'Prevalence of Healthcare-Associated Infections in NICU',
    abstract: 'Analysis of healthcare-associated infection rates in neonatal ICU over 36 months with intervention effectiveness assessment.',
    research_category: 'Clinical Research',
    department_id: 'd3',
    principal_investigator_name: 'Dr. Hana Al-Otaibi',
    start_date: '2023-06-01',
    expected_completion_date: '2024-12-01',
    actual_completion_date: '2024-11-30',
    status: 'completed',
    workflow_stage: 'published',
    priority_level: 'high',
    completion_percentage: 100,
    irb_approval_status: 'approved',
    department_approval_status: 'approved',
    ethics_approval_status: 'approved',
    funding_source: 'Hospital Research Fund',
    budget: 95000,
    budget_currency: 'SAR',
    publication_status: 'published',
    journal_name: 'Journal of Infection Prevention',
    publication_date: '2025-01-15',
    doi: '10.1177/1757177424001122',
    impact_factor: 1.8,
    citation_count: 3,
    journal_quartile: 'Q2',
    indexed_database: 'Scopus',
    is_open_access: false,
    is_public: true,
    is_archived: false,
    created_at: '2023-06-01',
    updated_at: '2025-01-20',
  },
  {
    id: 'r8',
    research_id: 'PMNH-2026-0008',
    title: 'AI-Assisted Radiology Diagnosis for Early Cancer Detection',
    abstract: 'Pilot study on implementing AI-assisted diagnostic tools for early detection of oncological conditions in radiology.',
    research_category: 'Translational Research',
    department_id: 'd9',
    principal_investigator_name: 'Dr. Ibrahim Al-Dosari',
    start_date: '2026-01-15',
    expected_completion_date: '2027-06-15',
    status: 'active',
    workflow_stage: 'ethics_irb_approval',
    priority_level: 'critical',
    completion_percentage: 10,
    irb_approval_status: 'pending',
    department_approval_status: 'approved',
    ethics_approval_status: 'pending',
    funding_source: 'Saudi Vision 2030 Health Initiative',
    budget: 380000,
    budget_currency: 'SAR',
    publication_status: 'not_submitted',
    journal_name: 'Radiology',
    journal_quartile: 'Q1',
    indexed_database: 'ISI',
    is_open_access: false,
    is_public: false,
    is_archived: false,
    citation_count: 0,
    notes: 'High-priority project under Vision 2030 initiative. Ethics committee review scheduled.',
    created_at: '2026-01-15',
    updated_at: '2026-05-10',
  },
]

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1', user_id: 'u1',
    title: 'Deadline Alert: PMNH-2024-0002',
    message: 'Research "Nursing Staff Burnout" is 45 days past expected completion date. Immediate review required.',
    type: 'delay', priority: 'high', is_read: false,
    action_url: '/research/r2', created_at: '2026-05-17T09:00:00Z',
  },
  {
    id: 'n2', user_id: 'u1',
    title: 'IRB Approval Pending',
    message: 'Research "AI-Assisted Radiology Diagnosis" has been pending IRB approval for 30 days.',
    type: 'approval', priority: 'medium', is_read: false,
    action_url: '/research/r8', created_at: '2026-05-16T14:30:00Z',
  },
  {
    id: 'n3', user_id: 'u1',
    title: 'New Publication Confirmed',
    message: 'Research PMNH-2024-0001 has been successfully published in Saudi Medical Journal.',
    type: 'publication', priority: 'normal', is_read: true,
    read_at: '2026-05-15T10:00:00Z', action_url: '/research/r1', created_at: '2026-05-15T08:00:00Z',
  },
  {
    id: 'n4', user_id: 'u1',
    title: 'Upcoming Deadline: 7 Days',
    message: 'Research "Cardiac Rehabilitation Program" data collection milestone is due in 7 days.',
    type: 'deadline', priority: 'medium', is_read: false,
    action_url: '/research/r5', created_at: '2026-05-18T07:00:00Z',
  },
  {
    id: 'n5', user_id: 'u1',
    title: 'QR Code Scan - New Submission',
    message: 'A new research submission was received via QR code scan. Project: PMNH-2026-0009.',
    type: 'qr_submission', priority: 'normal', is_read: false,
    created_at: '2026-05-18T06:30:00Z',
  },
]

export const DEMO_ACTIVITY_LOGS: ActivityLog[] = [
  { id: 'a1', user_id: 'u1', user_name: 'Sultan Alallah', action: 'login', entity_type: 'auth', description: 'User logged in successfully', ip_address: '192.168.1.100', created_at: '2026-05-18T08:30:00Z' },
  { id: 'a2', user_id: 'u4', user_name: 'Afnan Bakri', action: 'update', entity_type: 'research_project', entity_id: 'r2', entity_name: 'Nursing Staff Burnout', description: 'Updated workflow stage to data_analysis', created_at: '2026-05-17T15:20:00Z' },
  { id: 'a3', user_id: 'u3', user_name: 'Dr. Khalid Al-Ghamdi', action: 'upload', entity_type: 'attachment', entity_id: 'r3', entity_name: 'Antibiotic Resistance - Manuscript Draft.docx', description: 'Uploaded manuscript draft', created_at: '2026-05-17T11:45:00Z' },
  { id: 'a4', user_id: 'u1', user_name: 'Sultan Alallah', action: 'create', entity_type: 'research_project', entity_id: 'r8', entity_name: 'AI-Assisted Radiology Diagnosis', description: 'Created new research project', created_at: '2026-05-16T09:00:00Z' },
  { id: 'a5', user_id: 'u2', user_name: 'Dr. Fatima Al-Zahrani', action: 'download', entity_type: 'report', description: 'Downloaded Annual Research Analytics Report', created_at: '2026-05-15T14:00:00Z' },
  { id: 'a6', user_id: 'u1', user_name: 'Sultan Alallah', action: 'qr_scan', entity_type: 'qr_code', entity_id: 'r1', description: 'QR code scanned for research PMNH-2024-0001', created_at: '2026-05-14T10:30:00Z' },
]

export const DEMO_STATS: DashboardStats = {
  total_projects: 108,
  active_projects: 74,
  completed_projects: 27,
  published_papers: 19,
  delayed_projects: 8,
  pending_irb: 5,
  upcoming_deadlines: 12,
  total_departments: 14,
  total_users: 87,
  this_month_new: 6,
  funded_projects: 42,
  total_budget: 4850000,
  q1_publications: 7,
  q2_publications: 6,
  q3_publications: 4,
  q4_publications: 2,
  open_access_count: 9,
}

export const DEMO_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ai1',
    type: 'warning',
    title: 'High Delay Risk Detected',
    message: '3 research projects in the Nursing department are showing 15+ days delay in data collection phase. Intervention recommended.',
    action: 'View Delayed Projects',
    department_id: 'd6',
    score: 87,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'ai2',
    type: 'recommendation',
    title: 'IRB Approval Optimization',
    message: 'Based on historical data, submitting IRB applications 6 weeks before study start increases approval rate by 34%. 2 pending studies should prioritize this.',
    action: 'Review IRB Queue',
    score: 72,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'ai3',
    type: 'success',
    title: 'Cardiology Research Excellence',
    message: 'Cardiology department has a 78% Q1 publication rate — highest in the hospital. This methodology should be shared with other departments.',
    action: 'View Department Analytics',
    department_id: 'd7',
    score: 95,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'ai4',
    type: 'info',
    title: 'Predicted Completion Date',
    message: 'Research PMNH-2024-0002 (Nursing Staff Burnout) is predicted to complete by Aug 2026 based on current progress velocity (65% done, 2.3% weekly progress).',
    action: 'View Research',
    research_id: 'r2',
    score: 68,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'ai5',
    type: 'recommendation',
    title: 'Publication Success Pattern',
    message: 'Research projects with ≥90 days of manuscript review show 2.3x higher Q1 acceptance rate. 4 current projects are rushing manuscript submission.',
    action: 'View Manuscripts',
    score: 79,
    created_at: '2026-05-18T08:00:00Z',
  },
  {
    id: 'ai6',
    type: 'warning',
    title: 'Missing Documentation Alert',
    message: '5 research projects are missing Ethics approval documentation. This may delay publication in indexed journals.',
    action: 'Review Documents',
    score: 91,
    created_at: '2026-05-18T08:00:00Z',
  },
]

export const MONTHLY_RESEARCH_DATA = [
  { month: 'Jan', new: 4, completed: 2, published: 1 },
  { month: 'Feb', new: 6, completed: 3, published: 2 },
  { month: 'Mar', new: 5, completed: 4, published: 1 },
  { month: 'Apr', new: 8, completed: 2, published: 3 },
  { month: 'May', new: 7, completed: 5, published: 2 },
  { month: 'Jun', new: 9, completed: 3, published: 4 },
  { month: 'Jul', new: 6, completed: 4, published: 2 },
  { month: 'Aug', new: 10, completed: 6, published: 1 },
  { month: 'Sep', new: 7, completed: 4, published: 3 },
  { month: 'Oct', new: 8, completed: 5, published: 2 },
  { month: 'Nov', new: 5, completed: 3, published: 1 },
  { month: 'Dec', new: 6, completed: 4, published: 2 },
]

export const DEPT_PERFORMANCE_DATA = [
  { dept: 'Nursing', projects: 15, published: 4, score: 88 },
  { dept: 'Int. Med', projects: 12, published: 3, score: 82 },
  { dept: 'Lab', projects: 11, published: 2, score: 79 },
  { dept: 'Cardiology', projects: 9, published: 4, score: 91 },
  { dept: 'Pediatrics', projects: 10, published: 2, score: 75 },
  { dept: 'Surgery', projects: 8, published: 2, score: 77 },
]
